tailor_distro/debian_templates/Dockerfile.j2
Re: https://github.com/ros2/ros2/issues/512
Not providing a version will install the latest one, which is likely a bad idea for interop with other libraries.
=> Install the bare minimum setuptools for colcon

setup.cfg
Getting the following error:
```
[2019-10-21T02:04:15.311Z] pkg_resources.ContextualVersionConflict: (rosdistro 0.7.5 (ci_tailor-distro_0.1.15/tailor-distro/.eggs/rosdistro-0.7.5-py3.6.egg), Requirement.parse('rosdistro==0.7.4'), {'tailor-distro'})
```
Tested the change on toydistro and it fixes the issue.
=> Bump rosdistro version

README.md, tailor_distro/__init__.py, tailor_distro/manage/__init__.py, tailor_distro/manage/base.py, tailor_distro/manage/compare.py, tailor_distro/manage/import_.py, tailor_distro/manage/pin.py, tailor_distro/manage/query.py, tailor_distro/manage/release.py, tailor_distro/manage/rosdistro_repo.py
The `rosdistro` Python package does not make use of the `PyGithub` and as a result `rosdistro.get_index` does not have the ability to read or write private github files. 
However, `tailor` does use `PyGithub` and has mechanisms for reading private files. This PR does four things with this idea. 
1. The default operation assumes `rosdistro_path` is the current directory or otherwise specified. If that doesn't work, it will throw an error. The first change is to make it so that if it doesn't exist, the [`get_index_url`](https://github.com/ros-infrastructure/rosdistro/blob/master/src/rosdistro/__init__.py#L71) functionality is used instead.
1. Creates `load_private_raw_file` which replaces [`load_url`](https://github.com/ros-infrastructure/rosdistro/blob/master/src/rosdistro/loader.py#L46) …
=> Access to Private Github Files

Jenkinsfile, tailor_distro/__init__.py, tailor_distro/debian_templates/Dockerfile.j2, tailor_distro/mirror_upstream.py, tailor_distro/publish_packages.py
Second attempt at this. This time, each release_label will have it's own separated folder for mirrors, bundles, images, etc
Tested here: http://tailor.locusbots.io/blue/organizations/jenkins/ci%2Ftoydistro/detail/feature%2Fper-release-version/3/pipeline
=> Use release-version instead of release-track

Jenkinsfile
Use a single timestamp for all the different pipelines. I've tested this on toydistro http://tailor.locusbots.io/blue/organizations/jenkins/ci%2Ftoydistro/detail/master/656/pipeline
=> Use timestamp from parameters

tailor_distro/debian_templates/rules.j2
This was breaking certain ROS2 modules for me after our move to focal
=> Make sure __pycache__ and pyc don't make it into deb

Jenkinsfile
I've wrapped all of the docker calls with a retry, similar to what we do on tailor-image to try and continue if we get a docker error.
Test is running [here](http://tailor.locusbots.io/blue/organizations/jenkins/ci%2Ftailor-distro/detail/retry-on-fail/2/pipeline)
=> Add retries to docker commands

tailor_distro/manage/base.py, tailor_distro/manage/release.py
This PR includes:
* update the release verb to match the new process, which doesn't tag the repos on the first release, since it's a candidate, but once the desired release branch exists on the repo, it will tag the release.
* Add `--dry-run` argument for testing
* fixes issue with _replace not replacing in place
I've tested this on my machine and works as expected.
=> Update release process

environment/Dockerfile
Aptly is currently throwing errors due to xz not being available
=> Install xz for mirror creation

tailor_distro/debian_templates/rules.j2
This was corrupting cyclone, which is our first library that builds .so.0.0 type artifacts
=> Don't muck up .so.x libraries

setup.cfg, tailor_distro/create_recipes.py, tailor_distro/generate_bundle_templates.py, tailor_distro/manage/pin.py
This allows having a package in the bridge distribution to declare dependencies on packages in underlays - though this isn't full-featured enough to cause those packages to be pulled into the build.
=> Treat underlay packages as peers to allow rosdep to work

tailor_distro/debian_templates/rules.j2
Found a better way to exclude binary executables. I've created a feature branch and tested the generated bundle. I confirm that rviz2 works instead of throwing a segfault and rosrun (which is a python exec) is ignored as expected.
This fixes RST-6108
=> Don't touch executable files RST-6108

tailor_distro/debian_templates/Dockerfile.j2, tailor_distro/generate_bundle_templates.py
`apt-transport-s3` fails if the `Region` isn't set on the config file
=> Add required Region to s3-apt config

environment/Dockerfile
The version bundled with focal seems to be a very old one which is not supported when using on focal. We need to update the bundler for this to work on focal.
=> Fix bundler for focal

tailor_distro/create_recipes.py
If we ever want to run `create_recipes` on a Jammy instance, we will need to update collections to use the abstract base class, or abc.
Source: https://docs.python.org/3/library/collections.abc.html
This fixes the following error:
```
Traceback (most recent call last):
File "/home/locus/locus_dev/src/venv/bin/create_recipes", line 8, in <module>
sys.exit(main())
File "/home/locus/locus_dev/src/tailor-distro/tailor_distro/create_recipes.py", line 82, in main
sys.exit(create_recipes(**vars(args)))
File "/home/locus/locus_dev/src/tailor-distro/tailor_distro/create_recipes.py", line 53, in create_recipes
recipe = nested_update(recipes['common'], recipe_options)
File "/home/locus/locus_dev/src/tailor-distro/tailor_distro/create_recipes.py", line 19, in nested_update
if isinstance(v, …
```
=> Updating to ensure mapping from collections.abc

tailor_distro/manage/release.py
Tested with `tailor_manage release --distro ros1 --release 23.2 $packages --dry-run`
=> RST-9356 Parametrize release branch with distro name

Jenkinsfile
When the builds are running, the ccache gets 100% misses.
```
[2024-07-17T06:55:34.334Z] + ccache -s
[2024-07-17T06:55:34.334Z] Summary:
[2024-07-17T06:55:34.334Z]   Hits:                0 /  7076 (0.00 %)
[2024-07-17T06:55:34.334Z]     Direct:            0 /  7076 (0.00 %)
[2024-07-17T06:55:34.334Z]     Preprocessed:      0 /  7076 (0.00 %)
[2024-07-17T06:55:34.334Z]   Misses:           7076
[2024-07-17T06:55:34.334Z]     Direct:         7076
[2024-07-17T06:55:34.334Z]     Preprocessed:   7076
[2024-07-17T06:55:34.334Z] Primary storage:
[2024-07-17T06:55:34.334Z]   Hits:                0 / 14151 (0.00 %)
[2024-07-17T06:55:34.334Z]   Misses:          14151
[2024-07-17T06:55:34.334Z]   Cache size (GB):  4.46 /  5.00 (89.29 %)
[2024-07-17T06:55:34.334Z]   Cleanups:           21
```
Looking …
=> Specify CCACHE_DIR when building

Jenkinsfile
This is to ensure the cache does not get too big for our packages, since AWS only allows 5GB. We can keep this at 4GB, however if we want to increase it, we can test at a later date to fine the optimal value.
=> Test with max cache size

Jenkinsfile
ccache has a default size of 5GB and will keep the cache below that  value. If the Jenkins cache is smaller (e.g. 4GB) then the cache will be discarded any time it goes above 4GB. Instead we can decrease the ccache size so that the cache should always fit.
Follow up to https://github.com/locusrobotics/tailor-distro/pull/96
=> Match the ccache size to jenkins cache

Jenkinsfile
Testing to see if having a faster cache can at least prevent any timeouts on 5 mins on the job cacher plugin(default). 
Reference: https://plugins.jenkins.io/jobcacher/
https://github.com/jenkinsci/jobcacher-plugin/issues/75
=> Test with a different compression method

environment/Dockerfile, tailor_distro/debian_templates/Dockerfile.j2
Adding support for tailor-distro to use a different mirror. This has been running on the build farm currently, and things look to be okay, so this PR is to make things permanent.
=> Merge in different Mirror usage with Tailor-Distro

Jenkinsfile, environment/Dockerfile, tailor_distro/debian_templates/Dockerfile.j2
The current flag --cache-from given to the docker build command is not working. If we want to re-use previous docker images that we already have build when no change is made inside the dockerfile, then this PR makes that happen. When using the cache with Dockers, we need a balance between speed and working with stale apt packages. Thus, this PR tries to prevent having very old packages by invalidating the cache once a week. Moreover, it exposes a new parameter to invalidate the cache manually if required.
This PR does the following: 
* makes use of Docker cache when re-building the Docker images (**Note**: this is used both for the parent image as for the bundle images)
* exposes a new parameter named `invalidate_cache` to manually trigger the cache invalidation when needed
* uses a …
=> Use docker cache while still updating apt packages
